error

diff --git a/.github/workflows/conditional.yml b/.github/workflows/conditional.yml
--- a/.github/workflows/conditional.yml
+++ b/.github/workflows/conditional.yml
@@ -22,4 +22,6 @@ jobs:
         run: echo "Successful"
       - name: third setp (failure)
         if: failure()
-        run: echo "Failed previous step"
+        run: |
+          exit 1
+          echo "Failed previous step"
